apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: testflow
spec:
  flows:
    - route:
        from:
          uri: timer:test
          steps:
            - setBody:
                expression:
                  constant:
                    expression: Sample message
            - log:
                message: ${body}
            - pollEnrich:
                expression:
                  simple:
                    expression: file:file_src?noop=true
                aggregationStrategy: '#aggregator'
                timeout: '1000'
            - log:
                message: 'polled: ${body}'
          parameters:
            delay: '1000'
            period: '3000'
